export const MESSAGE_LIST_MAX_WIDTH = 860
export const MESSAGE_LIST_HORIZONTAL_PADDING = 20
export const MESSAGE_CONTENT_MAX_WIDTH =
  MESSAGE_LIST_MAX_WIDTH - MESSAGE_LIST_HORIZONTAL_PADDING * 2
export const CHAT_INPUT_MAX_WIDTH = MESSAGE_CONTENT_MAX_WIDTH
